version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: |
            cd PalPayPaymentsPlatform/backend
            npm install
      - run:
          name: Start backend
          command: |
            cd PalPayment/backend
            npm run dev

  frontend:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: |
            cd PalPayPaymentsPlatform/frontend
            npm install
      - run:
          name: Build frontend
          command: |
            cd PalPayment/frontend
            npm run start

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-frontend
      - build-backend
